/* ─────────────────────────────────────────────────────────────────────────────
   Designer – Built-in templates
   Each template is a Fabric.js JSON structure for common design types
   ───────────────────────────────────────────────────────────────────────────── */

import type { BuiltinTemplate, TemplateCategory } from "@/types/designer";
import { nanoid } from "nanoid";

// Helper to create unique IDs for objects
const uid = () => nanoid(8);

// ── Social Media Templates ──────────────────────────────────────────────────

const instagramQuotePost: BuiltinTemplate = {
  id: "tpl-ig-quote",
  name: "Inspirational Quote",
  category: "Social Media",
  presetKey: "instagramPost",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: "#1a1a2e",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Rect",
        left: 60,
        top: 60,
        width: 960,
        height: 960,
        rx: 24,
        ry: 24,
        fill: "transparent",
        stroke: "#e94560",
        strokeWidth: 3,
        id: uid(),
        customName: "Border",
      },
      {
        type: "IText",
        left: 540,
        top: 380,
        originX: "center",
        originY: "center",
        text: "Dream big.\nStart small.\nAct now.",
        fontFamily: "Georgia",
        fontSize: 64,
        fontWeight: "700",
        fill: "#ffffff",
        textAlign: "center",
        lineHeight: 1.4,
        id: uid(),
        customName: "Quote",
      },
      {
        type: "Rect",
        left: 440,
        top: 560,
        width: 200,
        height: 4,
        fill: "#e94560",
        id: uid(),
        customName: "Divider",
      },
      {
        type: "IText",
        left: 540,
        top: 620,
        originX: "center",
        originY: "center",
        text: "@yourbrand",
        fontFamily: "Inter",
        fontSize: 28,
        fill: "#cccccc",
        textAlign: "center",
        id: uid(),
        customName: "Handle",
      },
    ],
    background: "#1a1a2e",
  },
};

const instagramPromoPost: BuiltinTemplate = {
  id: "tpl-ig-promo",
  name: "Sale Promotion",
  category: "Social Media",
  presetKey: "instagramPost",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: "#ff6b35",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Circle",
        left: 540,
        top: 400,
        originX: "center",
        originY: "center",
        radius: 220,
        fill: "#ffffff",
        id: uid(),
        customName: "Circle Badge",
      },
      {
        type: "IText",
        left: 540,
        top: 360,
        originX: "center",
        originY: "center",
        text: "50%",
        fontFamily: "Inter",
        fontSize: 120,
        fontWeight: "900",
        fill: "#ff6b35",
        textAlign: "center",
        id: uid(),
        customName: "Discount",
      },
      {
        type: "IText",
        left: 540,
        top: 440,
        originX: "center",
        originY: "center",
        text: "OFF",
        fontFamily: "Inter",
        fontSize: 48,
        fontWeight: "700",
        fill: "#ff6b35",
        textAlign: "center",
        id: uid(),
        customName: "OFF Label",
      },
      {
        type: "IText",
        left: 540,
        top: 700,
        originX: "center",
        originY: "center",
        text: "MEGA SALE",
        fontFamily: "Inter",
        fontSize: 72,
        fontWeight: "900",
        fill: "#ffffff",
        textAlign: "center",
        charSpacing: 200,
        id: uid(),
        customName: "Title",
      },
      {
        type: "IText",
        left: 540,
        top: 800,
        originX: "center",
        originY: "center",
        text: "Limited time offer \u2022 Shop now",
        fontFamily: "Inter",
        fontSize: 28,
        fill: "#fff3e0",
        textAlign: "center",
        id: uid(),
        customName: "Subtitle",
      },
    ],
    background: "#ff6b35",
  },
};

const igStoryAnnouncement: BuiltinTemplate = {
  id: "tpl-ig-story",
  name: "Story Announcement",
  category: "Social Media",
  presetKey: "instagramStory",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1080,
        height: 1920,
        fill: "#0f0c29",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1080,
        height: 1920,
        fill: "rgba(0,0,0,0)",
        id: uid(),
        customName: "Overlay",
      },
      {
        type: "IText",
        left: 540,
        top: 600,
        originX: "center",
        originY: "center",
        text: "NEW",
        fontFamily: "Inter",
        fontSize: 32,
        fontWeight: "500",
        fill: "#a78bfa",
        textAlign: "center",
        charSpacing: 800,
        id: uid(),
        customName: "Label",
      },
      {
        type: "IText",
        left: 540,
        top: 740,
        originX: "center",
        originY: "center",
        text: "Something\nExciting\nis Coming",
        fontFamily: "Georgia",
        fontSize: 80,
        fontWeight: "700",
        fill: "#ffffff",
        textAlign: "center",
        lineHeight: 1.3,
        id: uid(),
        customName: "Heading",
      },
      {
        type: "Rect",
        left: 340,
        top: 1100,
        width: 400,
        height: 70,
        rx: 35,
        ry: 35,
        fill: "#a78bfa",
        id: uid(),
        customName: "Button BG",
      },
      {
        type: "IText",
        left: 540,
        top: 1135,
        originX: "center",
        originY: "center",
        text: "SWIPE UP",
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "700",
        fill: "#ffffff",
        textAlign: "center",
        charSpacing: 400,
        id: uid(),
        customName: "CTA",
      },
    ],
    background: "#0f0c29",
  },
};

// ── Marketing Templates ─────────────────────────────────────────────────────

const facebookAdBanner: BuiltinTemplate = {
  id: "tpl-fb-ad",
  name: "Product Ad Banner",
  category: "Marketing",
  presetKey: "facebookPost",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1200,
        height: 630,
        fill: "#f8f9fa",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 600,
        height: 630,
        fill: "#2563eb",
        id: uid(),
        customName: "Left Panel",
      },
      {
        type: "IText",
        left: 300,
        top: 180,
        originX: "center",
        originY: "center",
        text: "Introducing\nOur Latest\nProduct",
        fontFamily: "Inter",
        fontSize: 52,
        fontWeight: "800",
        fill: "#ffffff",
        textAlign: "center",
        lineHeight: 1.2,
        id: uid(),
        customName: "Headline",
      },
      {
        type: "Rect",
        left: 150,
        top: 400,
        width: 300,
        height: 60,
        rx: 8,
        ry: 8,
        fill: "#ffffff",
        id: uid(),
        customName: "CTA Button",
      },
      {
        type: "IText",
        left: 300,
        top: 430,
        originX: "center",
        originY: "center",
        text: "Learn More",
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "700",
        fill: "#2563eb",
        textAlign: "center",
        id: uid(),
        customName: "CTA Text",
      },
      {
        type: "Rect",
        left: 660,
        top: 65,
        width: 480,
        height: 500,
        rx: 16,
        ry: 16,
        fill: "#e2e8f0",
        id: uid(),
        customName: "Image Placeholder",
      },
      {
        type: "IText",
        left: 900,
        top: 315,
        originX: "center",
        originY: "center",
        text: "Your Image\nHere",
        fontFamily: "Inter",
        fontSize: 28,
        fill: "#94a3b8",
        textAlign: "center",
        id: uid(),
        customName: "Placeholder Text",
      },
    ],
    background: "#f8f9fa",
  },
};

// ── Video Templates ─────────────────────────────────────────────────────────

const youtubeThumb: BuiltinTemplate = {
  id: "tpl-yt-thumb",
  name: "Bold Thumbnail",
  category: "Video",
  presetKey: "youtubeThumbnail",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1280,
        height: 720,
        fill: "#dc2626",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "IText",
        left: 640,
        top: 280,
        originX: "center",
        originY: "center",
        text: "THIS\nCHANGED\nEVERYTHING",
        fontFamily: "Inter",
        fontSize: 96,
        fontWeight: "900",
        fill: "#ffffff",
        textAlign: "center",
        lineHeight: 1.1,
        stroke: "#000000",
        strokeWidth: 4,
        id: uid(),
        customName: "Title",
      },
      {
        type: "Rect",
        left: 940,
        top: 500,
        width: 300,
        height: 70,
        rx: 12,
        ry: 12,
        fill: "#fbbf24",
        id: uid(),
        customName: "Badge BG",
      },
      {
        type: "IText",
        left: 1090,
        top: 535,
        originX: "center",
        originY: "center",
        text: "MUST WATCH",
        fontFamily: "Inter",
        fontSize: 26,
        fontWeight: "800",
        fill: "#000000",
        textAlign: "center",
        id: uid(),
        customName: "Badge Text",
      },
    ],
    background: "#dc2626",
  },
};

// ── Presentation Templates ──────────────────────────────────────────────────

const presentationTitle: BuiltinTemplate = {
  id: "tpl-pres-title",
  name: "Title Slide",
  category: "Presentation",
  presetKey: "presentation",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1920,
        height: 1080,
        fill: "#0f172a",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 8,
        height: 1080,
        fill: "#3b82f6",
        id: uid(),
        customName: "Left Accent",
      },
      {
        type: "IText",
        left: 160,
        top: 360,
        text: "Presentation Title",
        fontFamily: "Inter",
        fontSize: 72,
        fontWeight: "800",
        fill: "#ffffff",
        id: uid(),
        customName: "Title",
      },
      {
        type: "IText",
        left: 160,
        top: 470,
        text: "Subtitle goes here \u2022 Your Name \u2022 Date",
        fontFamily: "Inter",
        fontSize: 28,
        fill: "#94a3b8",
        id: uid(),
        customName: "Subtitle",
      },
      {
        type: "Rect",
        left: 160,
        top: 560,
        width: 120,
        height: 4,
        fill: "#3b82f6",
        id: uid(),
        customName: "Divider",
      },
      {
        type: "IText",
        left: 160,
        top: 600,
        text: "Company Name",
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "500",
        fill: "#64748b",
        id: uid(),
        customName: "Company",
      },
    ],
    background: "#0f172a",
  },
};

// ── Print Templates ─────────────────────────────────────────────────────────

const businessCardTemplate: BuiltinTemplate = {
  id: "tpl-biz-card",
  name: "Modern Business Card",
  category: "Print",
  presetKey: "businessCard",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1050,
        height: 600,
        fill: "#ffffff",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 12,
        height: 600,
        fill: "#4f46e5",
        id: uid(),
        customName: "Left Accent",
      },
      {
        type: "IText",
        left: 60,
        top: 120,
        text: "Jane Smith",
        fontFamily: "Inter",
        fontSize: 42,
        fontWeight: "700",
        fill: "#1e293b",
        id: uid(),
        customName: "Name",
      },
      {
        type: "IText",
        left: 60,
        top: 180,
        text: "Creative Director",
        fontFamily: "Inter",
        fontSize: 22,
        fill: "#4f46e5",
        id: uid(),
        customName: "Title",
      },
      {
        type: "Rect",
        left: 60,
        top: 240,
        width: 80,
        height: 2,
        fill: "#e2e8f0",
        id: uid(),
        customName: "Divider",
      },
      {
        type: "IText",
        left: 60,
        top: 280,
        text: "jane@example.com\n+1 (555) 123-4567\nwww.example.com",
        fontFamily: "Inter",
        fontSize: 18,
        fill: "#64748b",
        lineHeight: 1.6,
        id: uid(),
        customName: "Contact Info",
      },
      {
        type: "Rect",
        left: 780,
        top: 180,
        width: 200,
        height: 200,
        rx: 100,
        ry: 100,
        fill: "#f1f5f9",
        id: uid(),
        customName: "Logo Placeholder",
      },
      {
        type: "IText",
        left: 880,
        top: 280,
        originX: "center",
        originY: "center",
        text: "LOGO",
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "700",
        fill: "#94a3b8",
        textAlign: "center",
        id: uid(),
        customName: "Logo Text",
      },
    ],
    background: "#ffffff",
  },
};

// ── Logo Templates ──────────────────────────────────────────────────────────

const logoMinimal: BuiltinTemplate = {
  id: "tpl-logo-min",
  name: "Minimal Logo",
  category: "Logo",
  presetKey: "logo",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 500,
        height: 500,
        fill: "#ffffff",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Circle",
        left: 250,
        top: 200,
        originX: "center",
        originY: "center",
        radius: 80,
        fill: "transparent",
        stroke: "#1e293b",
        strokeWidth: 6,
        id: uid(),
        customName: "Logo Circle",
      },
      {
        type: "Triangle",
        left: 250,
        top: 195,
        originX: "center",
        originY: "center",
        width: 70,
        height: 60,
        fill: "#4f46e5",
        id: uid(),
        customName: "Logo Mark",
      },
      {
        type: "IText",
        left: 250,
        top: 330,
        originX: "center",
        originY: "center",
        text: "BRAND",
        fontFamily: "Inter",
        fontSize: 48,
        fontWeight: "800",
        fill: "#1e293b",
        textAlign: "center",
        charSpacing: 600,
        id: uid(),
        customName: "Brand Name",
      },
      {
        type: "IText",
        left: 250,
        top: 380,
        originX: "center",
        originY: "center",
        text: "STUDIO",
        fontFamily: "Inter",
        fontSize: 18,
        fontWeight: "400",
        fill: "#64748b",
        textAlign: "center",
        charSpacing: 1200,
        id: uid(),
        customName: "Tagline",
      },
    ],
    background: "#ffffff",
  },
};

// ── Event Templates ─────────────────────────────────────────────────────────

const eventFlyer: BuiltinTemplate = {
  id: "tpl-event-flyer",
  name: "Event Flyer",
  category: "Event",
  presetKey: "instagramPost",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: "#0a0a0a",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "IText",
        left: 540,
        top: 200,
        originX: "center",
        originY: "center",
        text: "LIVE EVENT",
        fontFamily: "Inter",
        fontSize: 28,
        fontWeight: "500",
        fill: "#fbbf24",
        textAlign: "center",
        charSpacing: 1000,
        id: uid(),
        customName: "Tag",
      },
      {
        type: "IText",
        left: 540,
        top: 380,
        originX: "center",
        originY: "center",
        text: "Summer\nMusic\nFestival",
        fontFamily: "Georgia",
        fontSize: 96,
        fontWeight: "700",
        fill: "#ffffff",
        textAlign: "center",
        lineHeight: 1.1,
        id: uid(),
        customName: "Title",
      },
      {
        type: "Rect",
        left: 440,
        top: 600,
        width: 200,
        height: 3,
        fill: "#fbbf24",
        id: uid(),
        customName: "Divider",
      },
      {
        type: "IText",
        left: 540,
        top: 680,
        originX: "center",
        originY: "center",
        text: "JUNE 15 - 17, 2025",
        fontFamily: "Inter",
        fontSize: 30,
        fontWeight: "600",
        fill: "#ffffff",
        textAlign: "center",
        charSpacing: 200,
        id: uid(),
        customName: "Date",
      },
      {
        type: "IText",
        left: 540,
        top: 740,
        originX: "center",
        originY: "center",
        text: "Central Park \u2022 New York",
        fontFamily: "Inter",
        fontSize: 22,
        fill: "#a3a3a3",
        textAlign: "center",
        id: uid(),
        customName: "Location",
      },
      {
        type: "Rect",
        left: 340,
        top: 830,
        width: 400,
        height: 65,
        rx: 8,
        ry: 8,
        fill: "#fbbf24",
        id: uid(),
        customName: "CTA BG",
      },
      {
        type: "IText",
        left: 540,
        top: 862,
        originX: "center",
        originY: "center",
        text: "GET TICKETS",
        fontFamily: "Inter",
        fontSize: 22,
        fontWeight: "700",
        fill: "#0a0a0a",
        textAlign: "center",
        charSpacing: 300,
        id: uid(),
        customName: "CTA Text",
      },
    ],
    background: "#0a0a0a",
  },
};

// ── LinkedIn Templates ──────────────────────────────────────────────────────

const linkedinBanner: BuiltinTemplate = {
  id: "tpl-linkedin-banner",
  name: "Professional Banner",
  category: "Business",
  presetKey: "linkedinBanner",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1584,
        height: 396,
        fill: "#0f172a",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "Rect",
        left: 0,
        top: 356,
        width: 1584,
        height: 40,
        fill: "#3b82f6",
        id: uid(),
        customName: "Bottom Accent",
      },
      {
        type: "IText",
        left: 100,
        top: 120,
        text: "Your Name Here",
        fontFamily: "Inter",
        fontSize: 56,
        fontWeight: "800",
        fill: "#ffffff",
        id: uid(),
        customName: "Name",
      },
      {
        type: "IText",
        left: 100,
        top: 200,
        text: "Software Engineer \u2022 Designer \u2022 Creator",
        fontFamily: "Inter",
        fontSize: 26,
        fill: "#94a3b8",
        id: uid(),
        customName: "Title",
      },
      {
        type: "Rect",
        left: 100,
        top: 260,
        width: 80,
        height: 3,
        fill: "#3b82f6",
        id: uid(),
        customName: "Divider",
      },
      {
        type: "IText",
        left: 100,
        top: 290,
        text: "Building the future, one pixel at a time.",
        fontFamily: "Inter",
        fontSize: 20,
        fontStyle: "italic",
        fill: "#64748b",
        id: uid(),
        customName: "Tagline",
      },
    ],
    background: "#0f172a",
  },
};

// ── Twitter / X Templates ───────────────────────────────────────────────────

const twitterBanner: BuiltinTemplate = {
  id: "tpl-twitter-post",
  name: "Twitter Post Card",
  category: "Social Media",
  presetKey: "twitterPost",
  fabricJson: {
    version: "7.0.0",
    objects: [
      {
        type: "Rect",
        left: 0,
        top: 0,
        width: 1600,
        height: 900,
        fill: "#1e1b4b",
        selectable: false,
        id: uid(),
        customName: "Background",
      },
      {
        type: "IText",
        left: 800,
        top: 320,
        originX: "center",
        originY: "center",
        text: "Hot Take",
        fontFamily: "Inter",
        fontSize: 96,
        fontWeight: "900",
        fill: "#ffffff",
        textAlign: "center",
        id: uid(),
        customName: "Title",
      },
      {
        type: "IText",
        left: 800,
        top: 440,
        originX: "center",
        originY: "center",
        text: "Your bold opinion goes right here.\nMake it short. Make it sharp.",
        fontFamily: "Inter",
        fontSize: 32,
        fill: "#c7d2fe",
        textAlign: "center",
        lineHeight: 1.5,
        id: uid(),
        customName: "Body",
      },
      {
        type: "IText",
        left: 800,
        top: 680,
        originX: "center",
        originY: "center",
        text: "@handle",
        fontFamily: "Inter",
        fontSize: 24,
        fill: "#818cf8",
        textAlign: "center",
        id: uid(),
        customName: "Handle",
      },
    ],
    background: "#1e1b4b",
  },
};

// ── Blank Templates ─────────────────────────────────────────────────────────

const blankInstagram: BuiltinTemplate = {
  id: "tpl-blank-ig",
  name: "Blank Canvas",
  category: "Social Media",
  presetKey: "instagramPost",
  fabricJson: {
    version: "7.0.0",
    objects: [],
    background: "#ffffff",
  },
};

const blankPresentation: BuiltinTemplate = {
  id: "tpl-blank-pres",
  name: "Blank Presentation",
  category: "Presentation",
  presetKey: "presentation",
  fabricJson: {
    version: "7.0.0",
    objects: [],
    background: "#ffffff",
  },
};

// ── Export all templates ─────────────────────────────────────────────────────

export const BUILTIN_TEMPLATES: BuiltinTemplate[] = [
  blankInstagram,
  blankPresentation,
  instagramQuotePost,
  instagramPromoPost,
  igStoryAnnouncement,
  facebookAdBanner,
  youtubeThumb,
  presentationTitle,
  businessCardTemplate,
  logoMinimal,
  eventFlyer,
  linkedinBanner,
  twitterBanner,
];

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  "Social Media",
  "Marketing",
  "Video",
  "Presentation",
  "Print",
  "Logo",
  "Event",
  "Business",
];

/**
 * Get templates filtered by category. Pass null/undefined for all.
 */
export function getTemplatesByCategory(
  category?: TemplateCategory | null,
): BuiltinTemplate[] {
  if (!category) return BUILTIN_TEMPLATES;
  return BUILTIN_TEMPLATES.filter((t) => t.category === category);
}
